// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehyjpoauwmnckppxuaic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeWpwb2F1d21uY2twcHh1YWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTgwMTAsImV4cCI6MjA2MjkzNDAxMH0.Hj2hQFSL_28XSfprYskMTik9142tpzSF3jQffqyCxpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);